[package]
name = "cxrs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", default-features = true, features = ["clock"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
